"""
BABSHARQII v13.0 — Agent Creator
منشئ الوكلاء — إنشاء وكلاء جدد من وصف نصي

Flow:
1. User describes the desired agent in natural language
2. AgentCreator uses LLM to generate REAL agent logic for the execute() method
3. Agent code is assembled from a dynamic template + LLM-generated body
4. Agent is tested in SandboxRunner
5. Agent is registered in AGIBridge (with human approval)
6. Agent becomes available for use

Security:
- All new agents require human approval via ApprovalGate
- New agents start with zero permissions (TimeBoundedPolicy)
- Agent code is tested in sandbox before registration
- LLM-generated code is sanitized (no os.system, no subprocess, no eval/exec)

Feature Flag: MAMOUN_SELF_PROGRAMMING (default: false)
"""

import os
import re
import time
import json
import uuid
import logging
from dataclasses import dataclass, field, asdict
from typing import Optional
from pathlib import Path

from mamoun.evolution.self_programming_loop import SELF_PROGRAMMING_ENABLED, _is_self_programming_enabled

logger = logging.getLogger(__name__)

AGENTS_DIR = str(Path(__file__).parent.parent / "agents")

# Patterns that are FORBIDDEN in LLM-generated agent code for security
FORBIDDEN_CODE_PATTERNS = [
    r"os\.system\s*\(",
    r"subprocess\.",
    r"eval\s*\(",
    r"exec\s*\(",
    r"__import__\s*\(",
    r"open\s*\(.+['\"]w['\"]",
    r"shutil\.rmtree",
    r"os\.remove\s*\(",
    r"os\.unlink\s*\(",
    r"import\s+pickle",
    r"pickle\.loads?\s*\(",
    r"ctypes\.",
    r"socket\s*\(",
    r"requests\.(post|put|delete|patch)\s*\(",
    r"httpx\.(post|put|delete|patch)\s*\(",
]


def _sanitize_generated_code(code: str) -> str:
    """
    تنظيف الكود المولّد — Remove dangerous patterns from LLM-generated code.

    Returns:
        Sanitized code string with dangerous patterns removed/replaced.
    """
    for pattern in FORBIDDEN_CODE_PATTERNS:
        match = re.search(pattern, code)
        if match:
            logger.warning(f"Blocked forbidden pattern in generated code: {match.group()}")
            # Replace the dangerous call with a safe comment
            code = re.sub(pattern, f"# BLOCKED_UNSAFE_CALL  # was: {match.group()}", code)
    return code


# ─────────────────────────────────────────────────────────────────────────────
# Agent Skeleton Template (dynamic — execute body is LLM-generated)
# ─────────────────────────────────────────────────────────────────────────────

AGENT_SKELETON_TEMPLATE = '''"""
BABSHARQII v13.0 — {agent_name}
{description_ar}

Auto-generated by AgentCreator with LLM-powered logic.
Feature Flag: MAMOUN_{flag_name} (default: false)
"""

import os
import time
import logging
from dataclasses import dataclass, field, asdict
from typing import Optional

logger = logging.getLogger(__name__)

{flag_constant} = os.getenv("MAMOUN_{flag_name}", "false").lower() in ("true", "1", "yes")


@dataclass
class {class_name}Config:
    """إعدادات {agent_name}."""
    name: str = "{agent_name}"
    name_ar: str = "{name_ar}"
    enabled: bool = False
    max_retries: int = 3
    timeout_seconds: float = 60.0

    def to_dict(self) -> dict:
        return asdict(self)


class {class_name}:
    """
    {agent_name} — {description_ar}

    {description_en}
    """

    def __init__(self, config: {class_name}Config = None):
        self._config = config or {class_name}Config()
        self._initialized = False
        self._task_count = 0
        self._error_count = 0

    async def initialize(self):
        """تهيئة الوكيل."""
        if self._initialized:
            return
        self._initialized = True
        logger.info(f"{class_name}: Initialized")

    async def execute(self, task: str, context: dict = None) -> dict:
        """
        تنفيذ مهمة — Execute a task.

        Args:
            task: وصف المهمة
            context: سياق إضافي

        Returns:
            Task result
        """
        await self.initialize()
        context = context or {{}}

        if not {flag_constant}:
            return {{
                "success": False,
                "error": "{agent_name} غير مفعّل. قم بتعيين MAMOUN_{flag_name}=true",
            }}

        self._task_count += 1
        start_time = time.time()

        try:
{execute_body}

            duration_ms = (time.time() - start_time) * 1000
            result["duration_ms"] = round(duration_ms, 1)

            return result

        except Exception as e:
            self._error_count += 1
            logger.error(f"{{self._config.name}}: Task error: {{e}}")
            return {{
                "success": False,
                "error": str(e)[:500],
                "agent": self._config.name,
            }}

    def get_status(self) -> dict:
        """حالة الوكيل."""
        return {{
            "name": self._config.name,
            "name_ar": self._config.name_ar,
            "enabled": {flag_constant},
            "initialized": self._initialized,
            "task_count": self._task_count,
            "error_count": self._error_count,
        }}

    async def shutdown(self):
        """إيقاف الوكيل — يتوافق مع القانون 5."""
        self._initialized = False
        logger.info(f"{{self._config.name}}: Shutdown complete (Law 5 compliant)")
'''


# ─────────────────────────────────────────────────────────────────────────────
# Smart fallback execute body — used when LLM is unavailable
# ─────────────────────────────────────────────────────────────────────────────

FALLBACK_EXECUTE_BODY_TEMPLATE = '''            # LLM was unavailable — using capability-based fallback logic
            result = {{
                "success": True,
                "task": task,
                "agent": self._config.name,
                "capabilities": {capabilities_list},
            }}

            # Dispatch based on task keywords and declared capabilities
            task_lower = task.lower()
            handled = False

            for cap in {capabilities_list}:
                if cap.lower() in task_lower:
                    handled = True
                    result["matched_capability"] = cap
                    result["action_taken"] = f"Processed task via {{cap}} capability"
                    logger.info(f"{{self._config.name}}: Matched capability '{{cap}}' for task")
                    break

            if not handled:
                # Attempt generic processing based on the most relevant capability
                if {capabilities_list}:
                    primary_cap = {capabilities_list}[0]
                    result["matched_capability"] = primary_cap
                    result["action_taken"] = f"Processed task using primary capability: {{primary_cap}}"
                    logger.info(f"{{self._config.name}}: Using primary capability '{{primary_cap}}'")
                else:
                    result["action_taken"] = "No specific capability matched — task acknowledged"
                    logger.info(f"{{self._config.name}}: No capability matched for task")

            # Include context data if provided
            if context:
                result["context_keys"] = list(context.keys())
                result["context_included"] = True'''


# ─────────────────────────────────────────────────────────────────────────────
# LLM Prompt for generating agent execute() body
# ─────────────────────────────────────────────────────────────────────────────

LLM_SYSTEM_PROMPT = """You are an expert Python code generator for an AI agent framework called BABSHARQII.
Your task is to generate the BODY of an async execute() method for a Python agent class.

RULES:
1. Generate ONLY the Python code that goes INSIDE the try block of execute(), AFTER `self._task_count += 1` and `start_time = time.time()`.
2. The code must set a variable called `result` which is a dict with at minimum: {"success": True/False, "task": task, "agent": self._config.name}
3. You must NOT include the try/except boilerplate — that is already in the template.
4. Use proper Python indentation (12 spaces for the first level inside try, since the template has that indent).
5. You may use: `task` (str), `context` (dict), `self._config`, `self._config.name`, `self._config.name_ar`, `self._config.max_retries`, `self._config.timeout_seconds`, `logger`, `time`, `os`
6. Do NOT use: os.system, subprocess, eval, exec, __import__, open for writing, shutil, socket, pickle, ctypes, or any destructive operations.
7. Use logging: logger.info(), logger.warning(), logger.error() for important events.
8. Implement REAL logic based on the agent's description and capabilities — not just a placeholder.
9. If the agent has multiple capabilities, implement dispatch logic based on task content.
10. Include proper error handling within the body (try/except for sub-operations).
11. Return valid Python code only — no markdown, no explanation, no comments outside the code.
12. Do NOT include `import` statements — all needed imports are already in the template.
13. The code must be async-compatible (use await if calling async functions).
"""

LLM_USER_PROMPT_TEMPLATE = """Generate the execute() method body for this agent:

Agent Name: {agent_name}
Description (EN): {description_en}
Description (AR): {description_ar}
Capabilities: {capabilities}

The method signature is:
    async def execute(self, task: str, context: dict = None) -> dict:

Variables already in scope:
- task: str — the task description
- context: dict or {{}} — additional context
- self._config: the agent config with .name, .name_ar, .max_retries, .timeout_seconds
- logger: logging.Logger
- time: the time module
- start_time: float — already set to time.time()

Requirements:
- Set `result` dict with at least: {{"success": True/False, "task": task, "agent": self._config.name}}
- Implement REAL functional logic based on the description
- Handle errors gracefully within the body
- Use logger for important events
- Do NOT include the outer try/except (already provided by the template)

Generate ONLY the code that goes inside the try block (indented at 12 spaces):"""


@dataclass
class AgentCreationRequest:
    """طلب إنشاء وكيل جديد."""
    request_id: str = ""
    agent_name: str = ""
    agent_name_ar: str = ""
    description_en: str = ""
    description_ar: str = ""
    capabilities: list = field(default_factory=list)
    required_permissions: list = field(default_factory=list)
    priority: str = "medium"
    status: str = "proposed"
    generated_file: str = ""
    generated_class: str = ""
    llm_generated: bool = False
    llm_model_used: str = ""
    test_results: dict = field(default_factory=dict)
    approval_id: str = ""
    created_at: float = 0.0

    def __post_init__(self):
        if not self.request_id:
            self.request_id = f"agent_req_{uuid.uuid4().hex[:8]}"
        if not self.created_at:
            self.created_at = time.time()

    def to_dict(self) -> dict:
        return asdict(self)


class AgentCreator:
    """
    منشئ الوكلاء — ينشئ وكلاء جدد من وصف نصي باستخدام LLM.

    Steps:
    1. Parse description and extract agent specification
    2. Use LLM to generate REAL execute() method body
    3. Assemble Python agent file from skeleton template + LLM-generated body
    4. Sanitize generated code for security
    5. Test agent in sandbox
    6. Register with human approval via ApprovalGate
    7. Add to AGIBridge capability registry

    Usage:
        creator = AgentCreator()
        request = await creator.create_agent(
            agent_name="SentimentAnalyzer",
            agent_name_ar="محلل المشاعر",
            description_en="Analyzes sentiment in Arabic text using keyword extraction and polarity scoring",
            description_ar="يحلل المشاعر في النصوص العربية",
            capabilities=["sentiment_analysis", "arabic_nlp", "polarity_scoring"],
        )
    """

    def __init__(self, approval_gate=None, sandbox_runner=None):
        self._approval_gate = approval_gate
        self._sandbox_runner = sandbox_runner
        self._created_agents: dict[str, AgentCreationRequest] = {}
        self._creation_count = 0
        self._llm_generation_count = 0
        self._llm_failure_count = 0

    async def _generate_agent_logic(
        self,
        agent_name: str,
        description_en: str,
        description_ar: str,
        capabilities: list,
    ) -> tuple[str, bool, str]:
        """
        توليد منطق الوكيل باستخدام LLM — Generate the execute() method body via LLM.

        Args:
            agent_name: اسم الوكيل (English)
            description_en: وصف الوكيل بالإنجليزية
            description_ar: وصف الوكيل بالعربية
            capabilities: قدرات الوكيل

        Returns:
            Tuple of (execute_body_code, was_llm_generated, llm_model_used)
        """
        capabilities_str = json.dumps(capabilities, ensure_ascii=False) if capabilities else "[]"

        try:
            from mamoun.core.llm_client import get_llm_client, LLMMessage

            llm = get_llm_client()

            # Build the LLM prompt
            user_prompt = LLM_USER_PROMPT_TEMPLATE.format(
                agent_name=agent_name,
                description_en=description_en,
                description_ar=description_ar,
                capabilities=capabilities_str,
            )

            logger.info(f"AgentCreator: Calling LLM to generate execute() body for {agent_name}")

            response = await llm.chat(
                messages=[
                    LLMMessage(role="system", content=LLM_SYSTEM_PROMPT),
                    LLMMessage(role="user", content=user_prompt),
                ],
                model="glm-5.1",
                temperature=0.2,
                max_tokens=2048,
            )

            if not response.text or not response.text.strip():
                logger.warning(f"AgentCreator: LLM returned empty response for {agent_name}, using fallback")
                return self._generate_fallback_logic(capabilities), False, ""

            generated_code = response.text.strip()

            # Strip markdown code fences if present
            if generated_code.startswith("```python"):
                generated_code = generated_code[len("```python"):]
            elif generated_code.startswith("```"):
                generated_code = generated_code[len("```"):]
            if generated_code.endswith("```"):
                generated_code = generated_code[:-len("```")]
            generated_code = generated_code.strip()

            # Sanitize the generated code for security
            generated_code = _sanitize_generated_code(generated_code)

            # Validate basic structure — must contain 'result' assignment
            if "result" not in generated_code:
                logger.warning(
                    f"AgentCreator: LLM-generated code for {agent_name} missing 'result' variable, using fallback"
                )
                return self._generate_fallback_logic(capabilities), False, ""

            # Ensure proper indentation (12 spaces for code inside try block)
            # The LLM may generate with different indentation, so normalize it
            lines = generated_code.split("\n")
            normalized_lines = []
            for line in lines:
                if line.strip() == "":
                    normalized_lines.append("")
                    continue
                # If line starts with less than 12 spaces, add indentation
                stripped = line.lstrip()
                current_indent = len(line) - len(stripped)
                if current_indent < 12:
                    # Add indent to reach at least 12 spaces
                    line = " " * (12 - current_indent) + line
                normalized_lines.append(line)

            normalized_code = "\n".join(normalized_lines)

            self._llm_generation_count += 1
            logger.info(
                f"AgentCreator: LLM successfully generated execute() body for {agent_name} "
                f"(model={response.model}, tokens={response.tokens_used})"
            )

            return normalized_code, True, response.model

        except ImportError:
            logger.warning("AgentCreator: LLM client not available (ImportError), using fallback logic")
            return self._generate_fallback_logic(capabilities), False, ""

        except Exception as e:
            self._llm_failure_count += 1
            logger.error(f"AgentCreator: LLM generation failed for {agent_name}: {e}")
            return self._generate_fallback_logic(capabilities), False, ""

    def _generate_fallback_logic(self, capabilities: list) -> str:
        """
        توليد منطق احتياطي — Generate fallback execute() body when LLM is unavailable.

        This creates smart capability-based dispatch logic that routes tasks
        to the appropriate capability handler based on keyword matching.

        Args:
            capabilities: قائمة القدرات

        Returns:
            Python code string for the execute() body
        """
        capabilities_list = json.dumps(capabilities, ensure_ascii=False) if capabilities else "[]"

        body = FALLBACK_EXECUTE_BODY_TEMPLATE.format(capabilities_list=capabilities_list)

        return body

    async def create_agent(
        self,
        agent_name: str,
        agent_name_ar: str = "",
        description_en: str = "",
        description_ar: str = "",
        capabilities: list = None,
        required_permissions: list = None,
    ) -> dict:
        """
        إنشاء وكيل جديد — Create a new agent from description using LLM.

        Args:
            agent_name: اسم الوكيل (English, PascalCase)
            agent_name_ar: اسم الوكيل (Arabic)
            description_en: وصف الوكيل (English)
            description_ar: وصف الوكيل (Arabic)
            capabilities: قدرات الوكيل
            required_permissions: الصلاحيات المطلوبة

        Returns:
            Creation result with file path and status
        """
        if not _is_self_programming_enabled():
            return {
                "success": False,
                "error": "البرمجة الذاتية معطلة — تحتاج MAMOUN_SELF_PROGRAMMING=true",
            }

        # Validate agent name
        if not agent_name or not agent_name.replace("_", "").isalnum():
            return {
                "success": False,
                "error": "اسم الوكيل غير صالح — يجب أن يكون بالإنجليزية بدون مسافات",
            }

        # Validate description
        if not description_en and not description_ar:
            return {
                "success": False,
                "error": "يجب تقديم وصف للوكيل على الأقل بلغة واحدة",
            }

        self._creation_count += 1

        # Create request
        request = AgentCreationRequest(
            agent_name=agent_name,
            agent_name_ar=agent_name_ar or agent_name,
            description_en=description_en,
            description_ar=description_ar or description_en,
            capabilities=capabilities or [],
            required_permissions=required_permissions or [],
        )

        # Generate class name from agent name
        class_name = agent_name.replace("_", " ").title().replace(" ", "") + "Agent"

        # Generate flag name
        flag_name = agent_name.upper()
        flag_constant = f"{flag_name}_ENABLED"

        # ── Step 1: Generate execute() body via LLM ──────────────────────────
        logger.info(f"AgentCreator: Generating logic for {agent_name} (capabilities: {capabilities or []})")

        execute_body, was_llm_generated, llm_model_used = await self._generate_agent_logic(
            agent_name=agent_name,
            description_en=description_en,
            description_ar=description_ar or description_en,
            capabilities=capabilities or [],
        )

        request.llm_generated = was_llm_generated
        request.llm_model_used = llm_model_used

        if was_llm_generated:
            logger.info(f"AgentCreator: {agent_name} logic generated by LLM (model: {llm_model_used})")
        else:
            logger.info(f"AgentCreator: {agent_name} logic using smart fallback template")

        # ── Step 2: Assemble the full agent file ─────────────────────────────
        code = AGENT_SKELETON_TEMPLATE.format(
            agent_name=agent_name,
            class_name=class_name,
            name_ar=agent_name_ar or agent_name,
            description_ar=description_ar or description_en,
            description_en=description_en,
            flag_name=flag_name,
            flag_constant=flag_constant,
            execute_body=execute_body,
        )

        # ── Step 3: Write the agent file ─────────────────────────────────────
        file_name = f"{agent_name.lower()}_agent.py"
        file_path = os.path.join(AGENTS_DIR, file_name)

        # Check if file already exists
        if os.path.exists(file_path):
            return {
                "success": False,
                "error": f"الوكيل موجود بالفعل: {file_path}",
            }

        # Write the generated code
        try:
            os.makedirs(os.path.dirname(file_path), exist_ok=True)
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(code)
        except Exception as e:
            return {
                "success": False,
                "error": f"فشل كتابة الملف: {e}",
            }

        request.generated_file = file_path
        request.generated_class = class_name

        # ── Step 4: Validate the generated code is syntactically valid ────────
        try:
            with open(file_path, "r", encoding="utf-8") as f:
                source_code = f.read()
            compile(source_code, file_path, "exec")
            logger.info(f"AgentCreator: {agent_name} code passed syntax validation")
        except SyntaxError as e:
            logger.error(f"AgentCreator: {agent_name} generated code has syntax error: {e}")
            # Remove the invalid file
            try:
                os.remove(file_path)
            except OSError:
                pass
            return {
                "success": False,
                "error": f"الكود المولّد يحتوي على خطأ نحوي: {e}",
                "syntax_error": str(e),
            }

        # ── Step 5: Submit for approval ──────────────────────────────────────
        if self._approval_gate:
            try:
                from mamoun.core.approval_gate import ApprovalRequest
                approval_request = ApprovalRequest(
                    change_type="new_agent",
                    target=file_path,
                    description=f"وكيل جديد: {agent_name_ar or agent_name} — {description_ar or description_en}",
                    risk_level="high",
                    details=json.dumps(request.to_dict(), ensure_ascii=False),
                )
                result = await self._approval_gate.request_approval(approval_request)
                request.approval_id = result.get("id", "")
                request.status = "pending_approval"
            except Exception as e:
                logger.warning(f"Failed to submit agent creation for approval: {e}")
                request.status = "approval_failed"

        self._created_agents[request.request_id] = request

        logger.info(f"AgentCreator: Created agent {agent_name} at {file_path} (llm={was_llm_generated})")

        return {
            "success": True,
            "request_id": request.request_id,
            "agent_name": agent_name,
            "class_name": class_name,
            "file_path": file_path,
            "flag_name": f"MAMOUN_{flag_name}",
            "status": request.status,
            "requires_approval": bool(self._approval_gate),
            "llm_generated": was_llm_generated,
            "llm_model_used": llm_model_used,
        }

    def get_created_agents(self) -> list[dict]:
        """الحصول على الوكلاء المنشأين."""
        return [a.to_dict() for a in self._created_agents.values()]

    def get_status(self) -> dict:
        """حالة المنشئ."""
        return {
            "enabled": SELF_PROGRAMMING_ENABLED,
            "agents_created": self._creation_count,
            "llm_generations": self._llm_generation_count,
            "llm_failures": self._llm_failure_count,
            "pending_agents": sum(
                1 for a in self._created_agents.values()
                if a.status == "pending_approval"
            ),
        }

    async def shutdown(self):
        """إيقاف المنشئ — يتوافق مع القانون 5."""
        logger.info("AgentCreator: Shutdown complete (Law 5 compliant)")
