import { NextRequest, NextResponse } from 'next/server';
import { writeFileSync, readFileSync, existsSync, mkdirSync } from 'fs';
import { join } from 'path';
import { execSync } from 'child_process';
import { BRAIN_KEY_MAP, BRAIN_NAMES, EXTRA_KEYS, maskKey, type KeyStore } from '@/lib/key-manager';

const PROJECT_ROOT = process.cwd();
const FRONTEND_ENV_PATH = join(PROJECT_ROOT, '.env.local');
const BACKEND_ENV_PATH = join(PROJECT_ROOT, 'backend', '.env');
const KEYS_JSON_PATH = join(PROJECT_ROOT, '.keys.json');

function readEnvFile(path: string): Record<string, string> {
  const result: Record<string, string> = {};
  if (!existsSync(path)) return result;
  try {
    const content = readFileSync(path, 'utf-8');
    for (const line of content.split('\n')) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) continue;
      const eqIndex = trimmed.indexOf('=');
      if (eqIndex > 0) {
        const key = trimmed.slice(0, eqIndex).trim();
        const value = trimmed.slice(eqIndex + 1).trim();
        result[key] = value;
      }
    }
  } catch { /* read error */ }
  return result;
}

function writeEnvFile(path: string, updates: Record<string, string>, managedKeys: string[]) {
  const existing = readEnvFile(path);
  const merged = { ...existing, ...updates };
  for (const key of managedKeys) {
    if (!merged[key]) delete merged[key];
  }
  const lines = [
    `# BABSHARQII v41.0 — Auto-generated by Unified Key Manager`,
    `# Updated: ${new Date().toISOString()}`,
    ``,
  ];
  for (const [key, value] of Object.entries(merged)) {
    lines.push(`${key}=${value}`);
  }
  try {
    const dir = join(path, '..');
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
    writeFileSync(path, lines.join('\n') + '\n', 'utf-8');
  } catch (e) {
    console.error(`[key-manager] Write failed ${path}:`, e);
  }
}

function readKeyStore(): KeyStore {
  if (!existsSync(KEYS_JSON_PATH)) return { keys: {}, updatedAt: new Date().toISOString() };
  try {
    return JSON.parse(readFileSync(KEYS_JSON_PATH, 'utf-8'));
  } catch {
    return { keys: {}, updatedAt: new Date().toISOString() };
  }
}

function writeKeyStore(store: KeyStore) {
  try {
    writeFileSync(KEYS_JSON_PATH, JSON.stringify(store, null, 2), 'utf-8');
  } catch (e) {
    console.error('[key-manager] Key store write failed:', e);
  }
}

function distributeKeys(store: KeyStore): { distributed: string[]; reloaded: boolean } {
  const distributed: string[] = [];
  const allEnvKeys = [...new Set([...Object.values(BRAIN_KEY_MAP), ...EXTRA_KEYS])];
  const envUpdates: Record<string, string> = {};

  for (const [brainId, apiKey] of Object.entries(store.keys)) {
    if (!apiKey || apiKey === '(محفوظ)' || apiKey.trim().length === 0) continue;
    const envVar = BRAIN_KEY_MAP[brainId];
    if (envVar) envUpdates[envVar] = apiKey;
  }

  if (store.gemini_proxy_url && store.gemini_proxy_url !== '(محفوظ)' && store.gemini_proxy_url.trim()) envUpdates['GEMINI_PROXY_URL'] = store.gemini_proxy_url;
  if (store.github_token && store.github_token !== '(محفوظ)' && store.github_token.trim()) envUpdates['MAMOUN_GITHUB_TOKEN'] = store.github_token;
  if (store.admin_password && store.admin_password !== '(محفوظ)' && store.admin_password.trim()) envUpdates['MAMOUN_ADMIN_PASSWORD'] = store.admin_password;

  // 1) Primary: .keys.json
  writeKeyStore(store);
  distributed.push('.keys.json');

  // 2) Frontend: .env.local
  const frontendEnv: Record<string, string> = { ...envUpdates };
  for (const [key, value] of Object.entries(envUpdates)) {
    frontendEnv[`NEXT_PUBLIC_${key}`] = value;
  }
  writeEnvFile(FRONTEND_ENV_PATH, frontendEnv, [...allEnvKeys, ...allEnvKeys.map(k => `NEXT_PUBLIC_${k}`)]);
  distributed.push('.env.local');

  // 3) Backend: backend/.env
  writeEnvFile(BACKEND_ENV_PATH, envUpdates, allEnvKeys);
  distributed.push('backend/.env');

  // 4) Runtime process.env
  for (const [key, value] of Object.entries(envUpdates)) {
    process.env[key] = value;
    process.env[`NEXT_PUBLIC_${key}`] = value;
  }
  distributed.push('process.env');

  // 5) Backend LLMClient reload
  let reloaded = false;
  try {
    const backendUrl = process.env.MAMOUN_BACKEND_URL || 'http://localhost:8000';
    const result = execSync(
      `curl -s -X POST ${backendUrl}/api/v2/api-keys/reload --max-time 5 2>/dev/null || echo '{"success":false}'`,
      { encoding: 'utf-8', timeout: 8000 }
    );
    const parsed = JSON.parse(result.trim());
    reloaded = !!parsed.success;
    if (reloaded) distributed.push('LLMClient');
  } catch { /* backend offline */ }

  return { distributed, reloaded };
}

export async function GET() {
  const store = readKeyStore();
  const frontendEnv = readEnvFile(FRONTEND_ENV_PATH);
  const backendEnv = readEnvFile(BACKEND_ENV_PATH);

  const brains: Record<string, {
    has_key: boolean; key_masked: string; env_var: string; brain_name: string;
    in_frontend: boolean; in_backend: boolean; in_keystore: boolean;
  }> = {};

  for (const [brainId, envVar] of Object.entries(BRAIN_KEY_MAP)) {
    const key = store.keys[brainId] || process.env[envVar] || frontendEnv[envVar] || backendEnv[envVar] || '';
    brains[brainId] = {
      has_key: !!key,
      key_masked: maskKey(key),
      env_var: envVar,
      brain_name: BRAIN_NAMES[brainId] || brainId,
      in_frontend: !!frontendEnv[envVar],
      in_backend: !!backendEnv[envVar],
      in_keystore: !!store.keys[brainId],
    };
  }

  const activeList = Object.entries(brains).filter(([, v]) => v.has_key).map(([id]) => ({ id, name: BRAIN_NAMES[id] }));

  return NextResponse.json({
    brains,
    gemini_proxy: !!(store.gemini_proxy_url || process.env.GEMINI_PROXY_URL),
    github_token: !!(store.github_token || process.env.MAMOUN_GITHUB_TOKEN),
    admin_password_set: !!(store.admin_password || process.env.MAMOUN_ADMIN_PASSWORD),
    last_updated: store.updatedAt,
    distribution: {
      keystore: existsSync(KEYS_JSON_PATH),
      frontend_env: existsSync(FRONTEND_ENV_PATH),
      backend_env: existsSync(BACKEND_ENV_PATH),
    },
    active_brains: activeList,
    total_active: activeList.length,
  });
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { keys = {}, gemini_proxy_url, github_token, admin_password } = body as {
      keys: Record<string, string>; gemini_proxy_url?: string; github_token?: string; admin_password?: string;
    };

    const store = readKeyStore();

    for (const [brainId, apiKey] of Object.entries(keys)) {
      if (!brainId || !BRAIN_KEY_MAP[brainId]) continue;
      // Accept any non-empty key — the frontend now only sends raw keys the user typed
      if (apiKey && apiKey.trim().length > 0 && apiKey !== '(محفوظ)') {
        store.keys[brainId] = apiKey.trim();
      }
    }

    if (gemini_proxy_url && gemini_proxy_url.trim() && gemini_proxy_url !== '(محفوظ)') store.gemini_proxy_url = gemini_proxy_url.trim();
    if (github_token && github_token.trim() && github_token !== '(محفوظ)') store.github_token = github_token.trim();
    if (admin_password && admin_password.trim() && admin_password !== '(محفوظ)') store.admin_password = admin_password.trim();

    store.updatedAt = new Date().toISOString();

    const { distributed, reloaded } = distributeKeys(store);

    const activeBrains: string[] = [];
    for (const [brainId, envVar] of Object.entries(BRAIN_KEY_MAP)) {
      if (store.keys[brainId] || process.env[envVar]) activeBrains.push(brainId);
    }

    const brainNamesStr = activeBrains.map(id => BRAIN_NAMES[id] || id).join('، ');

    return NextResponse.json({
      success: true,
      activated_brains: activeBrains,
      total_active: activeBrains.length,
      distributed_to: distributed,
      reload_ok: reloaded,
      message: `✅ تم حفظ وتوزيع المفاتيح فوراً على ${distributed.length} موقع — ${activeBrains.length}/5 أدمغة نشطة: ${brainNamesStr || 'أدخل مفاتيح API لتفعيل الأدمغة'}`,
    });
  } catch (error) {
    const msg = error instanceof Error ? error.message : 'Unknown error';
    return NextResponse.json({ success: false, message: `❌ خطأ: ${msg}` }, { status: 500 });
  }
}
